language: java
install: true

jdk:
  - oraclejdk8
 # - oraclejdk9 -> this is not working yet
 # - oraclejdk10 -> this is not working yet

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    update: true

before_install:
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install ttf-mscorefonts-installer

script:
  - mvn clean install -B

after_success:
  - "[[ $TRAVIS_BRANCH == \"development\" ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -B -DskipTests -s settings.xml"
  - bash <(curl -s https://codecov.io/bash)