language: java
install: true

jdk:
  - oraclejdk8
  script:
    - mvn clean install -B

  - oraclejdk9
  script:
    - mvn clean install -B -P java9
    
 # - oraclejdk10 -> this is not working yet

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    update: true

before_install:
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install ttf-mscorefonts-installer

after_success:
  - "[[ $TRAVIS_BRANCH == \"development\" ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -B -DskipTests -s settings.xml"
  - bash <(curl -s https://codecov.io/bash)